# Gitlab CI 
# Build and Test pipeline for Python

image: "python:3.9"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - Test

pylint:
  stage: Test
  script:
    - pylint src/*.py
  allow_failure: true